name: Build

on:
  push:
  pull_request:    # For as and when merges are done

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt/CMake dependencies
        uses: jurplel/install-qt-action@v4
        # with:
          # qt-version: "6.6.1"

      - name: Install Ninja (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Install Ninja (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja

      - name: Configure
        run: cmake -S . -B build -G Ninja

      - name: Build
        run: cmake --build build

      - name: Deploy macOS app
        if: runner.os == 'macOS'
        run: macdeployqt build/hello_qt.app -verbose=2

      - name: Upload macOS artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: hello_qt-macos
          path: build/hello_qt.app

      - name: Upload Linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: hello_qt-linux
          path: build/hello_qt
